const nameList = [
  "Aditi Sharma",
  "Aarav Patel",
  "Ananya Singh",
  "Arjun Kumar",
  "Ayesha Verma",
  "Aryan Gupta",
  "Bhavya Reddy",
  "Dev Khanna",
  "Dia Joshi",
  "Esha Malhotra",
  "Gaurav Mehta",
  "Gitanjali Desai",
  "Harsh Chawla",
  "Ishika Suri",
  "Jai Kapoor",
  "Kavya Trivedi",
  "Kunal Sharma",
  "Lavanya Menon",
  "Manish Singh",
  "Mira Shah",
  "Nikhil Verma",
  "Neha Kapoor",
  "Omkar Patel",
  "Oishi Banerjee",
  "Pranav Kumar",
  "Pooja Gupta",
  "Rahul Sharma",
  "Riya Chatterjee",
  "Rajeev Mehta",
  "Sanya Mehra",
  "Shashank Singh",
  "Swara Iyer",
  "Shivansh Gupta",
  "Tanvi Malik",
  "Tarun Reddy",
  "Uma Sharma",
  "Utkarsh Joshi",
  "Vanya Kapoor",
  "Varun Agarwal",
  "Vidya Nair",
  "Vikrant Singh",
  "Yash Rajput",
  "Yamini Patel",
  "Zoya Khan",
  "Zain Sheikh",
  "Amitabh Verma",
  "Anjali Yadav",
  "Arnav Deshmukh",
  "Asha Khurana",
  "Avinash Patel",
  "Bhavna Jain",
  "Chirag Mehta",
  "Divya Singh",
  "Dhruv Kumar",
  "Eesha Gupta",
  "Farhan Khan",
  "Fatima Sheikh",
  "Girish Iyer",
  "Gunjan Kapoor",
  "Himanshu Sharma",
  "Ishani Shah",
  "Jatin Verma",
  "Jyoti Trivedi",
  "Kabir Agarwal",
  "Kanika Nair",
  "Kartik Reddy",
  "Lalita Mehta",
  "Manoj Singh",
  "Meera Suri",
  "Naman Chatterjee",
  "Nehal Desai",
  "Nidhi Mehra",
  "Om Prakash",
  "Preeti Patel",
  "Prateek Sharma",
  "Radha Menon",
  "Rahul Kapoor",
  "Rashmi Malik",
  "Samir Khanna",
  "Sanya Mehrotra",
  "Tara Yadav",
  "Uday Kumar",
  "Urvashi Singh",
  "Veer Sharma",
  "Vidushi Gupta",
  "Vivek Verma",
  "Yashika Mehta",
  "Zara Khan",
];
export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

const randomMessages = [
  "Hello there!",
  "How's your day going?",
  "Did you know that honey never spoils?",
  "What's your favorite color?",
  "I'm here to chat anytime!",
  "Pizza or pasta?",
  "Did you hear about the new movie?",
  "Let's talk about something fun!",
  "Do you have a favorite book?",
  "Coffee or tea?",
  "Life is full of surprises!",
  "What's your go-to karaoke song?",
  "Sunsets are so magical.",
  "Let's dream big together!",
  "Chocolate or vanilla?",
  "Have you ever tried bungee jumping?",
  "I'm a fan of random facts!",
  "Tell me a joke!",
  "Dance like no one's watching!",
  "Rainy days are cozy, aren't they?",
  "What's the last song you listened to?",
  "I believe in you!",
  "Nature is the best artist.",
  "Pineapple on pizza: yes or no?",
  "Do you enjoy cooking?",
  "If you could time travel, where would you go?",
  "Let's make today amazing!",
  "What's your spirit animal?",
  "I'm here to spread positivity!",
  "Art can change the world.",
  "Waffles or pancakes?",
  "Be yourself; everyone else is already taken.",
  "What's the most adventurous thing you've done?",
  "Isn't technology fascinating?",
  "Smile, it's contagious!",
  "What's on your mind right now?",
  "Life is short, eat dessert first.",
  "Tell me about your favorite hobby.",
  "Let's create our own sunshine!",
  "The future is full of possibilities.",
  "Books open doors to new worlds.",
  "Hiking or beach day?",
  "Do you have a favorite quote?",
  "Never stop learning!",
  "Let's celebrate the little victories!",
  "Ice cream in winter, yay or nay?",
  "You're awesome just the way you are.",
  "What's your dream vacation?",
  "Pets make everything better.",
  "Isn't laughter the best medicine?",
  "Do you believe in aliens?",
  "What's your favorite childhood memory?",
  "Spontaneity is the spice of life!",
  "Chase your dreams!",
  "What's your comfort food?",
  "Life is a journey, not a destination.",
  "Do you enjoy stargazing?",
  "Let's embrace the beauty of imperfection.",
  "What's your favorite season?",
  "Don't forget to hydrate!",
  "What's your favorite type of music?",
  "Every day is a new beginning.",
  "Travel broadens the mind.",
  "Do you have a favorite app?",
  "You're stronger than you think.",
  "Chocolate chip cookies or brownies?",
  "Dream big, work hard.",
  "What's your favorite movie genre?",
  "Be the reason someone smiles today.",
  "Artificial intelligence is fascinating!",
  "What's your ideal weekend?",
  "Cats or dogs?",
  "Life's too short to be serious all the time.",
  "What's your favorite way to relax?",
  "Believe in the magic within you.",
  "Do you have a favorite childhood game?",
  "Pizza is always a good idea.",
  "What's your hidden talent?",
  "Let's be kind to ourselves.",
  "Sunrise or sunset?",
  "What's the last thing that made you laugh?",
  "You're making a difference in the world.",
  "Do you have a favorite quote?",
  "Let's spread kindness like confetti!",
  "What's your favorite thing about yourself?",
  "Adventure awaits!",
  "Hot chocolate or iced coffee?",
  "You're not alone; I'm here for you.",
  "What's your favorite holiday tradition?",
  "Life is an art; make it colorful!",
];

export const generateRandomMessage = () => {
  return randomMessages[Math.floor(Math.random() * randomMessages.length)];
};
